### ISSUE TITLE
Progress bar issue ?

### ISSUE THREAD

**Issue by qwrty-ftw** [OzzieIsaacs/pyload-NextTheme#1]
Hello,

seems my progress bar had a problem ?

https://image.noelshack.com/fichiers/2018/08/3/1519198469-capture.jpg

Any idea ?

btw, thank you for this theme, i love it !

qwrty

**Comment by OzzieIsaacs** [comment]
Which browser (and version) are you using. In Firefox it Looks okay

**Comment by qwrty-ftw** [comment]
I'm using Firefox 56.0

Try Safari Mobile, same problem, maybe i forgot a files, will try to re install theme.

**Comment by qwrty-ftw** [comment]
Same problem.

**Comment by OzzieIsaacs** [comment]
Sorry, missmerged with pyplex UI. Easiest way to fix would be to download 
https://github.com/OzzieIsaacs/pyload-NextTheme/blob/master/media/js/Next/home.js
and replace the original ../pyload/module/web/media/js/Next/home.js
Should now work again as before.

**Comment by qwrty-ftw** [comment]
It's OK now, thank you :)
