### ISSUE TITLE
jquery.peekabar.min.js missing

### ISSUE THREAD

**Issue by jahir** [OzzieIsaacs/pyload-NextTheme#2]
_templates/Next/base.html_:
`<script type="text/javascript" src="{{'/media/js/Next/jquery.peekabar.min.js'|url}}"></script>`
but _/media/js/Next/jquery.peekabar.min.js_ is missing. 
I symlinked it from ../pyplex/jquery.peekabar.min.js, seems to work for now...

**Comment by OzzieIsaacs** [comment]
Sorry, forgot to add it, is added now
